; Configuration for running folio

; === ENV ===
;
; Used for all sorts of switches in the application
; Supported values are "dev" and "prod"
env = "dev"

; === Logging ===
;
; Log output
; Valid options are 'php://stdout' or a path to a log file
logOutput = php://stdout

; === Database ===
;
; Database name
dbName = folio

; Database user
dbUser = user

; Database password
dbPass = password

; Database host
dbHost = localhost

; Database port
dbPort = 5432
