name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Or specify a version like 1.3

      - name: Install Dependencies
        run: bun i -D

      - name: Run Linter
        run: bun run lint

      - name: Run Tests
        run: bun test
